server{
        server_name api.site.local;
        listen 80;
        
        location / {
                proxy_pass http://127.0.0.1:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
		if ($request_method = 'OPTIONS') {
            		proxy_pass http://127.0.0.1:8080;
        	}
        }
	access_log /tmp/access.log;
	error_log /tmp/error.log;	
}